title: FaludiZ
description: Geodézia, Térfinformatika, Szoftverfejlesztés
theme: minima
lang: hu
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-tagging
  - jekyll-tagging-related_posts
  - jekyll-youtube
  - jekyll-feed
